export const femaleConfig = {
  weights: {
    'Carnal Tilt': 3,
    'Facial Thirds': 3,
    'Cheekbone Location': 2,
    'Interocular Distance': 1,
    'Jawline': 1.5,
    'Chin': 3,
    'Nose': 2,
  },
  params: {
    'Carnal Tilt': 10,
    'Facial Thirds': 500,
    'Cheekbone Location': 11,
    'Interocular Distance': 200,
    'Jawline': 200,
    'Chin': 1000,
    'Nose': 2000,
  },
  idealRatios: {
    'Facial Thirds': 1.374,
    'Interocular Distance': 0.321,
    'Jawline': 0.605,
    'Chin': 0.454,
    'Nose': 0.2045,
  },
  carnalTiltMultiplierFactor: 0.8,
  physicalRating: {
    idealBMI: 21.5,
    sigma: 1.5,
    heightPenaltyThreshold: 60,
    penaltyFactor: 0.5,
    heightBonusMin: 60,
    heightBonusMax: 66,
    maxHeightBonus: 10,
  },
  eyeColorScores: {
    blue: 10,
    green: 10,
    brown: 0,
    default: -5,
  },
  bonus: {
    heightThreshold: 66,
    eligibleEyeColors: ['blue', 'green'],
    bonusValue: 5,
  },
  overallRating: {
    faceRatingWeight: 0.65,
    physicalRatingWeight: 0.5,
  },
};